name: Build APK for Ahorcado

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential autoconf automake libtool \
            libssl-dev pkg-config libsdl2-dev zlib1g-dev
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Setup Android NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d $HOME/.buildozer/android/platform

      - name: Configure environment
        run: |
          export NDK=$HOME/.buildozer/android/platform/android-ndk-r25b
          export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
          export TARGET=armv7a-linux-androideabi
          export API=21
          export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
          export CFLAGS="-fPIC -target ${TARGET}${API} --sysroot=$TOOLCHAIN/sysroot"
          export LDFLAGS="-target ${TARGET}${API} --sysroot=$TOOLCHAIN/sysroot"
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CFLAGS=$CFLAGS" >> $GITHUB_ENV
          echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV

      - name: Build libffi from source
        run: |
          LIBFFI_DIR="$HOME/.buildozer/android/packages/libffi"
          mkdir -p $LIBFFI_DIR
          cd $LIBFFI_DIR
          
          git clone https://github.com/libffi/libffi.git
          cd libffi
          git checkout v3.4.6
          
          ./autogen.sh
          ./configure \
            --host=$TARGET \
            --build=x86_64-pc-linux-gnu \
            --prefix=$TOOLCHAIN/sysroot/usr \
            CC="$CC" \
            CFLAGS="$CFLAGS" \
            LDFLAGS="$LDFLAGS"
          
          make -j$(nproc)
          make install

      - name: Configure Buildozer
        run: |
          buildozer init || true
          cat << EOF >> buildozer.spec
          android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b
          requirements = python3,kivy==2.2.1,kivymd==2.0.1.dev0,pillow
          EOF

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
