name: Build APK for Ahorcado
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev zlib1g-dev autoconf automake libtool pkg-config
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Set up NDK environment
      run: |
        export NDK=$HOME/.buildozer/android/platform/android-ndk-r25b
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export API=21
        export TARGET=armv7a-linux-androideabi
        export CC=$TOOLCHAIN/bin/$TARGET$API-clang
        export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
        export AR=$TOOLCHAIN/bin/llvm-ar
        export LD=$TOOLCHAIN/bin/ld
        export STRIP=$TOOLCHAIN/bin/llvm-strip
        export RANLIB=$TOOLCHAIN/bin/llvm-ranlib

    - name: Download libffi manually
      run: |
        mkdir -p $HOME/.buildozer/android/packages/libffi
        cd $HOME/.buildozer/android/packages/libffi
        wget https://github.com/libffi/libffi/releases/download/v3.4.6/libffi-3.4.6.tar.gz
        tar -xzf libffi-3.4.6.tar.gz

    - name: Build libffi manually
      run: |
        cd $HOME/.buildozer/android/packages/libffi/libffi-3.4.6
        autoreconf --install
        ./configure --host=$TARGET --prefix=$HOME/.buildozer/android/platform/android-ndk-r25b/sysroot/usr
        make -j$(nproc)
        make install

    - name: Configure Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then buildozer init; fi
        sed -i 's/^requirements = .*/requirements = python3,kivy==2.2.1,kivymd==2.0.1.dev0,pillow/' buildozer.spec
        echo "android.enable_libffi_from_system = True" >> buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk

