name: Build APK
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Cambié a una versión compatible con Buildozer y python-for-android

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake libtool libffi-dev \
            build-essential git python3 python3-dev python3-pip \
            ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            zlib1g-dev libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            libsqlite3-dev libfreetype6-dev libjpeg-dev libpng-dev \
            libssl-dev cmake pkg-config openjdk-11-jdk zip unzip curl lld aidl

      - name: Upgrade pip and install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.33 setuptools

      - name: Configure Buildozer
        run: |
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec

      - name: Cache Buildozer and Python-for-Android
        uses: actions/cache@v4
        with:
          path: |
            .buildozer
            .gradle
            .cache
          key: ${{ runner.os }}-buildozer-${{ github.ref }}-${{ hashFiles('**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Build APK
        run: |
          buildozer --debug android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
