name: Build APK for Ahorcado

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential aidl libffi-dev libssl-dev autoconf libtool pkg-config
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
          sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Download libffi manually
        run: |
          mkdir -p $HOME/.buildozer/android/packages/libffi
          cd $HOME/.buildozer/android/packages/libffi
          wget https://github.com/libffi/libffi/releases/download/v3.4.4/libffi-3.4.4.tar.gz
          tar -xzf libffi-3.4.4.tar.gz

      - name: Update configure.ac for libffi
        run: |
          cd $HOME/.buildozer/android/packages/libffi/libffi-3.4.4
          autoreconf --install
          autoupdate
          autoreconf --install

      - name: Set up NDK environment
        run: |
          export NDK=$HOME/.buildozer/android/platform/android-ndk-r25b
          export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
          export API=21
          export TARGET=armv7a-linux-androideabi
          export AR=$TOOLCHAIN/bin/llvm-ar
          export CC=$TOOLCHAIN/bin/$TARGET$API-clang
          export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
          export LD=$TOOLCHAIN/bin/ld
          export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
          export STRIP=$TOOLCHAIN/bin/llvm-strip
          echo "NDK environment set up"

      - name: Build libffi manually
        run: |
          cd $HOME/.buildozer/android/packages/libffi/libffi-3.4.4
          ./configure --host=$TARGET --prefix=$HOME/.buildozer/android/platform/android-ndk-r25b/sysroot/usr
          make -j$(nproc)
          make install

      - name: Configure Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

          sed -i 's/^requirements = .*/requirements = python3,kivy==2.2.1,kivymd==2.0.1.dev0,pillow,sdl2_ttf==2.0.15/' buildozer.spec

          sed -i 's|^android.ndk_path =.*|android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk-r25b|' buildozer.spec
          sed -i 's|^android.sdk_path =.*|android.sdk_path = /home/runner/.buildozer/android/platform/android-sdk|' buildozer.spec

          echo "android.enable_libffi_from_system = True" >> buildozer.spec

          cat buildozer.spec

      - name: Create p4a hook for libffi
        run: |
          cat > enable_libffi_from_system.py << 'EOF'
          import os
          from pythonforandroid.hooks import HookClass

          class EnableLibffiFromSystem(HookClass):
              def __init__(self, *args, **kwargs):
                  super(EnableLibffiFromSystem, self).__init__(*args, **kwargs)
                  self._ctx = None

              def set_ctx(self, ctx):
                  self._ctx = ctx

              def prebuild_platform(self, ctx):
                  ctx.recipe_build_order.remove('libffi')
                  print("Removed libffi from build order to use system libffi")

          hook = EnableLibffiFromSystem()
          EOF

      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
