name: Build APK for Ahorcado

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential autoconf automake libtool \
            pkg-config zlib1g-dev libssl-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Setup Android NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d $HOME/.buildozer/android/platform

      - name: Configure toolchain
        run: |
          export NDK_ROOT="$HOME/.buildozer/android/platform/android-ndk-r25b"
          export TOOLCHAIN="$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64"
          export TARGET="armv7a-linux-androideabi"
          export API=21
          
          echo "CC=$TOOLCHAIN/bin/${TARGET}${API}-clang" >> $GITHUB_ENV
          echo "AR=$TOOLCHAIN/bin/llvm-ar" >> $GITHUB_ENV
          echo "STRIP=$TOOLCHAIN/bin/llvm-strip" >> $GITHUB_ENV
          echo "RANLIB=$TOOLCHAIN/bin/llvm-ranlib" >> $GITHUB_ENV
          echo "CFLAGS=-fPIC -target ${TARGET}${API} --sysroot=$TOOLCHAIN/sysroot" >> $GITHUB_ENV
          echo "LDFLAGS=-target ${TARGET}${API} --sysroot=$TOOLCHAIN/sysroot" >> $GITHUB_ENV

      - name: Build libffi
        run: |
          LIBFFI_DIR="$HOME/.buildozer/android/packages/libffi"
          mkdir -p $LIBFFI_DIR
          cd $LIBFFI_DIR
          
          git clone --depth 1 --branch v3.4.6 https://github.com/libffi/libffi.git
          cd libffi
          
          # Configuración explícita para cross-compiling
          ./autogen.sh
          ./configure \
            --host=${TARGET} \
            --build=x86_64-pc-linux-gnu \
            --disable-shared \
            --enable-static \
            --disable-dependency-tracking \
            --prefix=$TOOLCHAIN/sysroot/usr \
            CC="$CC" \
            AR="$AR" \
            STRIP="$STRIP" \
            RANLIB="$RANLIB" \
            CFLAGS="$CFLAGS" \
            LDFLAGS="$LDFLAGS" \
            ac_cv_func_memcpy=yes \
            ac_cv_func_memset=yes \
            ac_cv_build=x86_64-pc-linux-gnu \
            ac_cv_host=${TARGET} \
            ac_cv_target=${TARGET}

          make -j$(nproc)
          make install

      - name: Configure Buildozer
        run: |
          buildozer init || true
          cat << EOF > buildozer.spec
          [app]
          title = Ahorcado
          package.name = ahorcado
          source.dir = .
          version = 1.0
          requirements = python3,kivy==2.2.1,kivymd==2.0.1.dev0,pillow,sdl2_ttf==2.0.15
          android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b
          android.enable_libffi_from_system = True
          EOF

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
