name: Build APK for Ahorcado
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev autoconf libtool pkg-config
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
          sudo apt-get install -y libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          python -m pip install --upgrade pip
          pip install buildozer cython
          
      - name: Configure Buildozer
        run: |
          # Si no existe buildozer.spec, inicializar uno
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          
          # Configurar buildozer para usar una versión específica de libffi
          if grep -q "requirements =" buildozer.spec; then
            sed -i 's/^requirements = .*/& libffi==3.4.4/' buildozer.spec
          else
            echo "requirements = python3,kivy,kivymd,libffi==3.4.4" >> buildozer.spec
          fi
          
          # Configurar rutas de NDK y SDK
          sed -i 's|^android.ndk_path =.*|android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk-r25b|' buildozer.spec
          sed -i 's|^android.sdk_path =.*|android.sdk_path = /home/runner/.buildozer/android/platform/android-sdk|' buildozer.spec
          
          # Habilitar precompilados para libffi
          echo "p4a.bootstrap = sdl2" >> buildozer.spec
          echo "p4a.hook = enable_prebuilt_libffi" >> buildozer.spec
          
          # Mostrar el archivo buildozer.spec para verificar
          cat buildozer.spec
          
      
      - name: Build APK with Buildozer
        run: |
          buildozer -v android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
