name: Build APK for Ahorcado

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential autoconf automake libtool \
            pkg-config zlib1g-dev libssl-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            clang llvm

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Setup Android NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip -d $HOME/.buildozer/android/platform

      - name: Configure Android toolchain
        run: |
          export NDK_ROOT="$HOME/.buildozer/android/platform/android-ndk-r25b"
          export TOOLCHAIN="$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64"
          export TARGET="armv7a-linux-androideabi"
          export API=21
          
          echo "NDK_ROOT=$NDK_ROOT" >> $GITHUB_ENV
          echo "TOOLCHAIN=$TOOLCHAIN" >> $GITHUB_ENV
          echo "TARGET=$TARGET" >> $GITHUB_ENV
          echo "API=$API" >> $GITHUB_ENV
          echo "CC=$TOOLCHAIN/bin/${TARGET}${API}-clang" >> $GITHUB_ENV
          echo "CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++" >> $GITHUB_ENV
          echo "CFLAGS=-fPIC -target ${TARGET}${API} --sysroot=$TOOLCHAIN/sysroot" >> $GITHUB_ENV
          echo "LDFLAGS=-target ${TARGET}${API} --sysroot=$TOOLCHAIN/sysroot" >> $GITHUB_ENV

      - name: Build libffi from source
        run: |
          LIBFFI_DIR="$HOME/.buildozer/android/packages/libffi"
          mkdir -p $LIBFFI_DIR
          cd $LIBFFI_DIR
          
          # Clonar y compilar libffi desde el repositorio git
          git clone --depth 1 --branch v3.4.6 https://github.com/libffi/libffi.git
          cd libffi
          
          ./autogen.sh
          ./configure \
            --host=$TARGET \
            --build=x86_64-pc-linux-gnu \
            --prefix=$TOOLCHAIN/sysroot/usr \
            CC="$CC" \
            CFLAGS="$CFLAGS" \
            LDFLAGS="$LDFLAGS"
          
          make -j$(nproc)
          make install

      - name: Configure Buildozer
        run: |
          buildozer init || true
          cat << EOF > buildozer.spec
          [app]
          title = Ahorcado
          package.name = ahorcado
          package.domain = org.example
          source.dir = .
          version = 1.0
          requirements = python3,kivy==2.2.1,kivymd==2.0.1.dev0,pillow,sdl2_ttf==2.0.15
          android.ndk_path = $NDK_ROOT
          android.sdk_path = $HOME/.buildozer/android/platform/android-sdk
          android.enable_libffi_from_system = True
          EOF

      - name: Build Android APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
