name: Build Android APK
on: [push, pull_request]

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.33

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good

      - name: Install Android build dependencies
        run: |
          sudo apt-get install -y \
            openjdk-11-jdk \
            autoconf \
            automake \
            libtool \
            libffi-dev \
            libssl-dev \
            ccache \
            unzip \
            zip

      - name: Build APK
        run: |
          buildozer android debug
          echo "APK built successfully"
          find . -name "*.apk" -type f

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Copy APK to artifacts directory
        run: |
          cp bin/*.apk artifacts/ || echo "No APK found in bin directory"
          find . -name "*.apk" -type f -exec cp {} artifacts/ \;
          ls -la artifacts/

      # Usar una acción diferente para subir artefactos
      - name: Upload APK using actions/upload-artifact@v1
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: artifacts
