name: Build Android APK
on: [push, pull_request]

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0
          pip install cython==0.29.33

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good

      - name: Install Android build dependencies
        run: |
          sudo apt-get install -y \
            openjdk-11-jdk \
            autoconf \
            automake \
            libtool \
            libffi-dev \
            libssl-dev \
            ccache \
            unzip \
            zip

      # Instalar Android SDK explícitamente
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Instalar las build-tools específicamente
      - name: Install Android build-tools
        run: |
          yes | sdkmanager "build-tools;34.0.0"
          yes | sdkmanager "platforms;android-34"
          yes | sdkmanager "platform-tools"
          yes | sdkmanager "tools"
          yes | sdkmanager "ndk;25.2.9519653"
          yes | sdkmanager --licenses

      # Configurar buildozer.spec
      - name: Configure buildozer.spec
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i 's/^android.sdk_path =.*/android.sdk_path = \/usr\/local\/lib\/android\/sdk/' buildozer.spec
          sed -i 's/^android.ndk_path =.*/android.ndk_path = \/usr\/local\/lib\/android\/sdk\/ndk\/25.2.9519653/' buildozer.spec
          sed -i 's/^android.api =.*/android.api = 34/' buildozer.spec
          sed -i 's/^android.minapi =.*/android.minapi = 21/' buildozer.spec
          sed -i 's/^android.ndk =.*/android.ndk = 25.2.9519653/' buildozer.spec
          sed -i 's/^p4a.bootstrap =.*/p4a.bootstrap = sdl2/' buildozer.spec
          cat buildozer.spec

      # Construir APK con verbose para depuración
      - name: Build APK
        run: |
          buildozer -v android debug
          echo "APK built successfully"
          find . -name "*.apk" -type f

      # Listar archivos para depuración
      - name: List files
        run: |
          find . -name "*.apk" -type f
          ls -la bin/ || echo "bin directory not found"
